import '../models/quest.dart';

/// Toàn bộ nhiệm vụ của game (id khớp với `startQuests`/`completeQuests` trong story).
const allQuests = <Quest>[
  // HỒI 1
  Quest(
    id: 'Q1_GiaDinh',
    act: 1,
    type: QuestType.main,
    title: 'Đêm Gia Định Thất Thủ',
    description: 'Thoát khỏi thành Gia Định trước khi quân Tây Sơn siết chặt vòng vây.',
    unlockCondition: 'start',
    reward: 'Giữ được ngọn lửa hy vọng',
    rewardEffect: {'morale': 5},
  ),
  Quest(
    id: 'Q1_RaBien',
    act: 1,
    type: QuestType.side,
    title: 'Tìm Đường Ra Biển',
    description: 'Tìm được đường thoát ra biển, tới đảo Thổ Chu.',
    unlockCondition: 'complete:Q1_GiaDinh',
    reward: 'Thêm lương khô cho hành trình lưu vong',
    rewardEffect: {'food': 5},
  ),
  // HỒI 2
  Quest(
    id: 'Q2_VongLap',
    act: 2,
    type: QuestType.main,
    title: 'Vòng Lặp Được – Mất',
    description: 'Nhiều lần chiếm rồi lại mất Gia Định. Đứng dậy sau mỗi lần thất bại.',
    unlockCondition: 'complete:Q1_GiaDinh',
    reward: 'Bản lĩnh của người từng vấp ngã',
    rewardEffect: {'morale': 5},
  ),
  Quest(
    id: 'Q2_XiemLa',
    act: 2,
    type: QuestType.main,
    title: 'Lưu Vong Xiêm La',
    description: 'Tị nạn ở Xiêm, tìm cách giữ vững lực lượng và tình nghĩa.',
    unlockCondition: 'complete:Q2_VongLap',
    reward: 'Uy tín với triều Xiêm',
    rewardEffect: {'diplomacy': 5},
  ),
  Quest(
    id: 'Q2_RachGam',
    act: 2,
    type: QuestType.main,
    title: 'Thảm Bại Rạch Gầm',
    description: 'Đi cùng quân Xiêm vào trận Rạch Gầm – Xoài Mút, đối đầu Nguyễn Huệ.',
    unlockCondition: 'complete:Q2_VongLap',
    reward: 'Bài học đắt giá: không dựa vào đội quân mình không kiểm soát',
    rewardEffect: {'diplomacy': 3},
  ),
  // HỒI 3
  Quest(
    id: 'Q3_CauVien',
    act: 3,
    type: QuestType.main,
    title: 'Sứ Mệnh Cầu Viện',
    description: 'Cử Bá Đa Lộc cùng Hoàng tử Cảnh sang Pháp cầu viện.',
    unlockCondition: 'complete:Q2_XiemLa',
    reward: 'Hiệp ước Versailles và một số hỗ trợ quân sự',
    rewardEffect: {'diplomacy': 8},
  ),
  Quest(
    id: 'Q3_SiQuan',
    act: 3,
    type: QuestType.side,
    title: 'Chiêu Mộ Sĩ Quan Phương Tây',
    description: 'Mời các sĩ quan Pháp tình nguyện về giúp huấn luyện quân đội.',
    unlockCondition: 'complete:Q3_CauVien',
    reward: 'Kỹ thuật thành lũy, pháo binh hoặc thủy quân kiểu Tây',
    rewardEffect: {'army': 6},
  ),
  Quest(
    id: 'Q3_DaChieu',
    act: 3,
    type: QuestType.hidden,
    title: 'Góc Nhìn Đa Chiều',
    description: 'Xem xét việc cầu viện phương Tây từ nhiều phía: lợi ích, cái giá và lời phê phán.',
    unlockCondition: 'secret',
    reward: 'Hiểu sâu hơn một quyết định gây tranh cãi',
    rewardEffect: {'morale': 3, 'diplomacy': 3},
  ),
  // HỒI 4
  Quest(
    id: 'Q4_TroVe',
    act: 4,
    type: QuestType.main,
    title: 'Trở Về Gia Định',
    description: 'Tái chiếm Gia Định khi Nguyễn Huệ bận đối phó quân Thanh.',
    unlockCondition: 'complete:Q3_CauVien',
    reward: 'Một căn cứ để đứng vững',
    rewardEffect: {'morale': 8},
  ),
  Quest(
    id: 'Q4_CanCu',
    act: 4,
    type: QuestType.main,
    title: 'Xây Dựng Căn Cứ',
    description: 'Củng cố quân lực và lương thực để Gia Định đủ sức đối đầu Tây Sơn.',
    unlockCondition: 'complete:Q4_TroVe',
    reward: 'Kho lương đầy và quân đội hùng mạnh',
    rewardEffect: {'army': 5, 'food': 5},
  ),
  Quest(
    id: 'Q4_LongDan',
    act: 4,
    type: QuestType.side,
    title: 'Ổn Định Lòng Dân',
    description: 'Vỗ yên dân chúng sau chiến tranh để giữ được lòng người.',
    unlockCondition: 'complete:Q4_TroVe',
    reward: 'Dân chúng một lòng theo chúa',
    rewardEffect: {'morale': 8},
  ),
  // HỒI 5
  Quest(
    id: 'Q5_NoiLoan',
    act: 5,
    type: QuestType.side,
    title: 'Khai Thác Nội Loạn Tây Sơn',
    description: 'Lợi dụng mâu thuẫn trong triều Tây Sơn để suy yếu địch.',
    unlockCondition: 'start',
    reward: 'Quân địch ở Quy Nhơn suy yếu',
    rewardEffect: {},
  ),
  Quest(
    id: 'Q5_QuyNhon',
    act: 5,
    type: QuestType.main,
    title: 'Hạ Quy Nhơn',
    description: 'Đánh chiếm thành Quy Nhơn, kinh đô cũ của Nguyễn Nhạc.',
    unlockCondition: 'complete:Q4_CanCu',
    reward: 'Bàn đạp để tiến ra Bắc',
    rewardEffect: {'morale': 5},
  ),
  Quest(
    id: 'Q5_PhuXuan',
    act: 5,
    type: QuestType.main,
    title: 'Vây Phú Xuân',
    description: 'Phá thủy quân Tây Sơn ở Thị Nại và tiến chiếm Phú Xuân.',
    unlockCondition: 'complete:Q5_QuyNhon',
    reward: 'Kinh thành cũ của chúa Nguyễn trở về',
    rewardEffect: {'army': 5},
  ),
  // HỒI 6
  Quest(
    id: 'Q6_ThangLong',
    act: 6,
    type: QuestType.main,
    title: 'Trận Thăng Long',
    description: 'Đánh chiếm Thăng Long, chấm dứt nhà Tây Sơn và thống nhất đất nước.',
    unlockCondition: 'complete:Q5_PhuXuan',
    reward: 'Lên ngôi Gia Long — non sông thu về một mối',
    rewardEffect: {},
  ),
];

final Map<String, Quest> questsById = {for (final q in allQuests) q.id: q};
